
import type {Metadata} from 'next';
import './globals.css';
import ThemeUpdater from '@/components/theme-updater';
import MarketingScripts from '@/components/marketing-scripts';
import { Suspense } from 'react';
import SiteBranding from '@/components/site-branding';

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
        <ThemeUpdater />
        <SiteBranding />
        <Suspense fallback={null}>
          <MarketingScripts location="head" />
        </Suspense>
      </head>
      <body className="font-body antialiased">
        <Suspense fallback={null}>
          <MarketingScripts location="body" />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
